//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Users/bbdtest1/Documents/9.6-Alpha-9.6.0-(502).apk.
        /// </summary>
        public static string apkPath {
            get {
                return ResourceManager.GetString("apkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.6.0 (502).
        /// </summary>
        public static string apkVersion {
            get {
                return ResourceManager.GetString("apkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Emulator1 {
            get {
                return ResourceManager.GetString("Emulator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Emulator2 {
            get {
                return ResourceManager.GetString("Emulator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Emulator3 {
            get {
                return ResourceManager.GetString("Emulator3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODA External.
        /// </summary>
        public static string env {
            get {
                return ResourceManager.GetString("env", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Exectype {
            get {
                return ResourceManager.GetString("Exectype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contarctLimitlessVoic,0828743247
        ///contractUsername,0828718100
        ///env,LIVE PROD
        ///Exectype,Local
        ///GlobalPassword,Testing1
        ///HybridPassword,Testing1
        ///Hybridusername,0828717422
        ///HybridUsername1,0828717337
        ///LegacyContractUsername,0828716322
        ///nxllvlGiftusername,0828904447
        ///nxtLvlContractUsername,0637758906
        ///nxtlvlpassword,Testing1
        ///nxtlvlusername,0648419577
        ///otpbypassnum,0715135502
        ///Prepaidpassword,Testing1
        ///prepaidusername,0828718645
        ///prepaidUsername1,0828718662
        ///PrepaidUsername2,0828718662
        ///usedpin,952789378178
        ///n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LIVE_PROD {
            get {
                return ResourceManager.GetString("LIVE_PROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcometo,Welcome to
        ///MyVodacom,My Vodacom
        ///PleaseEnterNumberLabel,PleaseEnterNumberLabel
        ///Cellphonenumber,Cellphone number
        ///CellphoneNumberTextBox,CellphoneNumberTextBox
        ///ProceedButton,ProceedButton
        ///PasswordTextBox,PasswordTextBox
        ///UserNameTextBox,UserNameTextBox
        ///Loginto,Log in to
        ///Username,Username
        ///android.widget.ImageView,android.widget.ImageView
        ///Password,Password
        ///LoginButton,LoginButton
        ///Platform_DefaultRenderer,Platform_DefaultRenderer
        ///MenuButtonIcon,MenuButtonIcon
        ///FormsImageView,FormsImageView        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LIVE_PROD_OR {
            get {
                return ResourceManager.GetString("LIVE_PROD_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contarctLimitlessVoic,0828743247
        ///contractUsername,0828718100
        ///env,LIVE PROD
        ///Exectype,Local
        ///GlobalPassword,Testing1
        ///HybridPassword,Testing1
        ///Hybridusername,0828717422
        ///HybridUsername1,0828717337
        ///LegacyContractUsername,0828716322
        ///nxllvlGiftusername,0828904447
        ///nxtLvlContractUsername,0637758906
        ///nxtlvlpassword,Testing1
        ///nxtlvlusername,0648419577
        ///otpbypassnum,0715135502
        ///Prepaidpassword,Testing1
        ///prepaidusername,0828718662
        ///prepaidUsername1,0828718662
        ///PrepaidUsername2,0828718662
        ///usedpin,952789378178
        ///n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PRODA_External {
            get {
                return ResourceManager.GetString("PRODA_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcometo,Welcome to
        ///MyVodacom,My Vodacom
        ///PleaseEnterNumberLabel,PleaseEnterNumberLabel
        ///Cellphonenumber,Cellphone number
        ///CellphoneNumberTextBox,CellphoneNumberTextBox
        ///ProceedButton,ProceedButton
        ///PasswordTextBox,PasswordTextBox
        ///UserNameTextBox,UserNameTextBox
        ///Loginto,Log in to
        ///Username,Username
        ///android.widget.ImageView,android.widget.ImageView
        ///Password,Password
        ///LoginButton,LoginButton
        ///Platform_DefaultRenderer,Platform_DefaultRenderer
        ///MenuButtonIcon,MenuButtonIcon
        ///FormsImageView,FormsImageView        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PRODA_External_OR {
            get {
                return ResourceManager.GetString("PRODA_External_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contbundleusername,
        ///forgetpassnum,
        ///globpassword,
        ///Hybridnum,
        ///Hybridnumpass,
        ///linknum,
        ///nonmahbuybunnum,
        ///nxtlvlusername,
        ///otpbypassnum,
        ///prepaidbuybundusername,
        ///prepaidpass,
        ///prepaidusername,.
        /// </summary>
        public static string UAT_External {
            get {
                return ResourceManager.GetString("UAT_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UAT_OR {
            get {
                return ResourceManager.GetString("UAT_OR", resourceCulture);
            }
        }
    }
}
